# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-11-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201024_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile.gif', null=True, upload_to='images'),
        ),
    ]
